FROM node:22-alpine AS frontend-builder
WORKDIR /frontend
ARG APP_VERSION
ARG GIT_COMMIT
ARG GITHUB_SHA
ARG GIT_COMMIT_DATE
ARG BUILD_TIME
ENV APP_VERSION=${APP_VERSION}
ENV GIT_COMMIT=${GIT_COMMIT}
ENV GITHUB_SHA=${GITHUB_SHA}
ENV GIT_COMMIT_DATE=${GIT_COMMIT_DATE}
ENV BUILD_TIME=${BUILD_TIME}
COPY client/package*.json ./
RUN npm ci
COPY client/ ./
RUN npm run build

FROM nginx:alpine
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-builder /frontend/dist /usr/share/nginx/html
